### ISSUE TITLE
Servers claims stockholm-se.pirateirc.net to listen on 9090

### ISSUE THREAD

**Issue by Mikaela** [ppau/PirateIRC#17]
While all servers are listening only on 6697/TLS.

**Comment by Mikaela** [comment]
https://github.com/ppau/PirateIRC/commit/9929dc0fc9ee693dface9dd71ce9a8cf5a02917b

**Comment by FletcherAU** [comment]
https://github.com/ppau/PirateIRC/commit/9929dc0fc9ee693dface9dd71ce9a8cf5a02917b
