### ISSUE TITLE
News to add sometime

### ISSUE THREAD

**Issue by Mikaela** [ppau/PirateIRC#9]
* 2018-02-12: DroneBL was enabled.
* 2018-02-19: @AriMartti joined opers from PPFI.
* 2018-02-23: IP cloaking was disabled out of gateway. The pdf or some explanation?

**Comment by Mikaela** [comment]
Oh and I think we should also mention some story about HostServ (and why to not mention GroupServ) in the news too.

**Comment by FletcherAU** [comment]
https://github.com/ppau/PirateIRC/commit/0a0c4fdb8c27cbde1a3a1f07990a3ffdbb8d8904 has added drone, admin, and cloaking changes. Not sure what to say on Hostserv/Groupserv.

**Comment by Mikaela** [comment]
e.g.

> Vhosts are still available with HostServ (after identifying/registering to NickServ). To see vhosts available for you `/msg hostserv offerlist`, to start using one `/msg hostserv take copypaste.pirate`. We recommend configuring SASL for your client.

**Comment by FletcherAU** [comment]
https://github.com/ppau/PirateIRC/pull/10 added hostserv info and fixed AriMartti

**Comment by FletcherAU** [comment]
2b9735c
